# This workflow will build a Java project with Maven, and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-java-with-maven

# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Java CI with Maven

on:
  push:
    branches: [ "actions" ]
  pull_request:
    branches: [ "actions" ]
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven
    - name: Build with Maven
      run: mvn -B package --file pom.xml

    - name: Run tests
      run: mvn surefire:test -Dtest=AppTest

    - name: Upload Test Results
      uses: actions/upload-artifact@v4
      with:
        name: surefire-test-results
        path: target/surefire-reports/
    - name: Publish Test Results
      uses: EnricoMi/publish-unit-test-result-action@v2
      with:
        files: target/surefire-reports/TEST-*.xml


#    - name: Custom stage
#      run: |
#       echo "✅ Running Custom Stage..."
#       set -e  # Stop execution on any error
#       mkdir -p new  # Ensure 'new/' directory exists
#       cp -v target/*.jar new/ || { echo "❌ No JAR files found!"; exit 1; }
#       ls -la new/  # Debugging: Show copied files
#       ls -la target/
      
      
